name	'lesaux/bind-records'
version '0.0.1'
source	'git://github.com/inkblot/puppet-bind'
author	'inkblot'
license	'Apache 2.0'
summary 'manage BIND records'
description 'A Puppet module to manage dns record with nsupdate'
project_page 'https://github.com/inkblot/puppet-bind'

dependency 'puppetlabs/concat', '>= 1.0.0'
